language: elixir
elixir:
  - 1.7
env:
  - MIX_ENV=test
services: # ensure that Travis-CI provisions a DB for our tests
  - postgresql
script:
  - mix do deps.get, compile, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
